### ISSUE TITLE
missing file request

### ISSUE THREAD

**Issue by hcilab-cnu** [TaikiInoue/RIAD#1]
Hi, thanks for sharing your code.

I found that a file was missing in data loading mvtec as shown below.

*** df = pd.read_csv(self.data_dir / "info.csv")

Could you share the file?
Thank you!

**Comment by ds2268** [comment]
Any update on this? Seems like the dataset used (mvtec) is not used in the same way as the original one (not the same data structure). Is mvtec available in your format somewhere? Thanks! @taikiinoue45 @hcilab-cnu
