### ISSUE TITLE
where is the info.csv file in MVTecDataset?

### ISSUE THREAD

**Issue by Jingtao-Li-CVer** [TaikiInoue/RIAD#2]
Hi, thanks for your amazing work! I wonder where is the info.csv file.

I downloaded the MVTecDataset from https://www.mvtec.com/company/research/datasets/mvtec-ad

**Comment by taikiinoue45** [comment]
Data and info.csv are in docker image (taikiinoue45/mvtec:mvtec). Could you check [Dockerfile](https://github.com/taikiinoue45/RIAD/blob/main/docker/Dockerfile).

**Comment by taikiinoue45** [comment]
Here is how to create info.csv
https://github.com/taikiinoue45/mvtec-utils/blob/main/docker/prepare.py

**Comment by Jingtao-Li-CVer** [comment]
That helps me. Thanks!
